[package]
name = "c25519"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rand = { version = "^0.8" }

[dev-dependencies]
hex = { version = "^0.4" }
